#!/usr/bin/env node
/*
 * Gas -> USD cost model for the ChainAttest evaluation (paper Workstream R3).
 *
 * The public-testnet run (Sepolia) proves the flow executes on a real network, but
 * Sepolia ETH is valueless, so the *dollar* cost there is $0. To give a meaningful
 * deployment-cost figure, this script converts the measured on-chain gas into a
 * mainnet-equivalent USD cost across a small sensitivity grid of gas-price and
 * ETH-price scenarios. The gas numbers are real (from the comparative harness); the
 * price points are documented assumptions, not predictions.
 *
 *   cost_usd = gas * gasPriceGwei * 1e-9 (ETH/gas) * ethUsd
 *
 * Usage:
 *   node scripts/gas_to_usd.js
 *   GAS_SCENARIOS="5:2500,20:3000,50:4000" node scripts/gas_to_usd.js
 *     (each entry is gasPriceGwei:ethUsd)
 *
 * Emits: artifacts/eval/cost_model.json + cost_model.md
 */
"use strict";

const fs = require("fs");
const path = require("path");

const REPO_ROOT = path.join(__dirname, "..", "..");
const EVAL_DIR = path.join(REPO_ROOT, "artifacts", "eval");
const BASELINE = path.join(EVAL_DIR, "baseline_comparison.json");

// Documented illustrative scenarios (gasPriceGwei, ethUsd). Override with
// GAS_SCENARIOS="gwei:usd,gwei:usd,...". These are assumptions for a
// mainnet-equivalent estimate, not forecasts.
const DEFAULT_SCENARIOS = [
  { label: "low", gasPriceGwei: 5, ethUsd: 2500 },
  { label: "medium", gasPriceGwei: 20, ethUsd: 3000 },
  { label: "high", gasPriceGwei: 50, ethUsd: 4000 },
];

function parseScenarios() {
  const raw = process.env.GAS_SCENARIOS;
  if (!raw) return DEFAULT_SCENARIOS;
  return raw.split(",").map((entry, i) => {
    const [gwei, usd] = entry.split(":").map(Number);
    return { label: `s${i + 1}`, gasPriceGwei: gwei, ethUsd: usd };
  });
}

function usd(gas, gasPriceGwei, ethUsd) {
  return gas * gasPriceGwei * 1e-9 * ethUsd;
}

function main() {
  if (!fs.existsSync(BASELINE)) {
    throw new Error(
      `Missing ${path.relative(REPO_ROOT, BASELINE)}; run measure_baselines.ts first.`
    );
  }
  const baseline = JSON.parse(fs.readFileSync(BASELINE, "utf8"));
  const scenarios = parseScenarios();

  const evm = baseline.sources.evm;
  const fabric = baseline.sources.fabric;
  const items = [
    { name: "Attestation (ChainAttest, EVM source)", gas: Number(evm.attestation.chainattest_gas) },
    { name: "Attestation (ChainAttest, Fabric source)", gas: Number(fabric.attestation.chainattest_gas) },
    { name: "Attestation (generic bridge)", gas: Number(evm.attestation.generic_bridge_gas) },
    { name: "Attestation (naive anchor)", gas: Number(evm.attestation.naive_anchor_gas) },
    { name: "Eval claim (ChainAttest, EVM source)", gas: Number(evm.eval.chainattest_gas) },
    { name: "Eval claim (ChainAttest, Fabric source)", gas: Number(fabric.eval.chainattest_gas) },
    { name: "Eval claim (generic bridge)", gas: Number(evm.eval.generic_bridge_gas) },
    { name: "Eval claim (naive anchor)", gas: Number(evm.eval.naive_anchor_gas) },
  ];

  const rows = items.map((it) => ({
    name: it.name,
    gas: it.gas,
    usd: Object.fromEntries(
      scenarios.map((s) => [s.label, Number(usd(it.gas, s.gasPriceGwei, s.ethUsd).toFixed(4))])
    ),
  }));

  const summary = {
    generatedAt: new Date().toISOString(),
    note:
      "Mainnet-equivalent USD estimate from measured gas. On Sepolia the actual cost is $0 " +
      "(test ETH). Gas figures are real; gas-price/ETH-price points are documented assumptions.",
    scenarios,
    rows,
  };
  fs.mkdirSync(EVAL_DIR, { recursive: true });
  fs.writeFileSync(path.join(EVAL_DIR, "cost_model.json"), JSON.stringify(summary, null, 2) + "\n");

  const money = (v) => `\\$${v.toFixed(2)}`;
  const header = ["| Operation | Gas |", ...scenarios.map((s) => ` ${s.gasPriceGwei} gwei / \\$${s.ethUsd} |`)].join("");
  const sep = ["| --- | ---: |", ...scenarios.map(() => " ---: |")].join("");
  const lines = [
    "# ChainAttest Mainnet-Equivalent Cost Model",
    "",
    "Generated by `contracts/scripts/gas_to_usd.js`. Measured on-chain gas converted to a",
    "mainnet-equivalent USD cost across gas-price / ETH-price scenarios. **On the Sepolia",
    "public testnet the real cost is $0** (valueless test ETH); this table estimates what the",
    "same gas would cost on Ethereum mainnet. Gas numbers are real; price points are documented",
    "assumptions, not forecasts.",
    "",
    header,
    sep,
    ...rows.map((r) =>
      [`| ${r.name} | ${r.gas.toLocaleString("en-US")} |`, ...scenarios.map((s) => ` ${money(r.usd[s.label])} |`)].join("")
    ),
    "",
  ];
  fs.writeFileSync(path.join(EVAL_DIR, "cost_model.md"), lines.join("\n"));

  process.stdout.write(JSON.stringify(summary, null, 2) + "\n");
  process.stdout.write(`\nWrote ${path.join("artifacts", "eval", "cost_model.json")} and .md\n`);
}

main();
